[project]
name = "speech-cli"
version = "0.1.0"

dependencies = [
    "transformers",
    "torchaudio",
    "torch",
    "sentencepiece",
    "pyaudio",
    "numpy",
    "datasets",
    "speechrecognition",
    "scipy",
    "scikit-learn",
]

[project.scripts]
speech-cli = "speech_cli:main"
